name: postgres-backup

on:
  schedule:
    - cron: "30 4 5 * *"

  workflow_dispatch:

jobs:
  db-backup:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.POSTGRES_URL }}
      PG_VERSION: "17"

    steps:
      - name: Install PostgreSQL
        run: |
          sudo apt update
          yes '' | sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
          sudo apt install -y postgresql-client-${{ env.PG_VERSION }}

      - name: Set PostgreSQL binary path
        run: echo "POSTGRES=/usr/lib/postgresql/${{ env.PG_VERSION }}/bin" >> $GITHUB_ENV

      - name: Set file, folder and path variables
        run: |
          DATE_NAME="$(date +'%Y%m%d-%H%M')"
          FILE_NAME="IntelliTrans-PG-${DATE_NAME}"
          echo "DATE_NAME=${DATE_NAME}" >> $GITHUB_ENV
          echo "FILE_NAME=${FILE_NAME}" >> $GITHUB_ENV

      - name: Run pg_dump
        run: |
          $POSTGRES/pg_dump ${{ env.DATABASE_URL }} > "${{ env.FILE_NAME }}.sql"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE_NAME }}
          path: ${{ env.FILE_NAME }}.sql
          retention-days: 90
